version: "3"

services:
  main:
    build:
        context: .
        dockerfile: ./docker/main/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ".:/app"
    command: "streamlit run main_st.py"
